import type { Metadata } from 'next'
import { Advent_Pro, Geist } from 'next/font/google'
import './globals.css'
import { cn } from '@/lib/utils'

const geist = Geist({ subsets: ['latin'], variable: '--font-sans' })

const adventPro = Advent_Pro({
  subsets: ['latin'],
  variable: '--font-advent-pro',
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ko" className={cn(adventPro.variable, 'font-sans', geist.variable)}>
      <body vaul-drawer-wrapper="" className="bg-gray-100" suppressHydrationWarning>
        <div className="mx-auto min-h-screen w-full max-w-93.75 bg-[#FAF7F2]">
          <main className="w-full">{children}</main>
        </div>
      </body>
    </html>
  )
}
