import type { Metadata } from 'next'
import { Advent_Pro } from 'next/font/google'
import './globals.css'

const adventPro = Advent_Pro({
  subsets: ['latin'],
  variable: '--font-advent-pro',
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ko" className={`${adventPro.variable} `}>
      <body className="bg-white" suppressHydrationWarning>
        <div className="mx-auto min-h-screen w-full max-w-125 bg-[#FAF7F2]">
          <main className="w-full">{children}</main>
        </div>
      </body>
    </html>
  )
}
